from .life_span import combined_lifespan
from .roles import roles_router
from .users import users_router
from .permissions import permissions_router
from .departments import departments_router
from .expense_types import expense_types_router
from .payment_types import payment_types_router
from .clients import clients_router
from .buyers import buyers_router
from .suppliers import suppliers_router
from .requests import requests_router
from .files import files_router
from .contracts import contracts_router
from .logs import logs_router
from .statistics import statistics_router
from .accounting import accounting_router
from .settings import settings_router
from .budgets import budgets_router
from .transactions import transactions_router
from .transfers import transfers_router
from .payer_companies import payer_companies_router
from .limits import limits_router
from .purchase import purchase_router
from .countries import countries_router
from .cities import cities_router
from .financier_checks import checker_router
from .request_invoices import invoice_router